// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.AspNetCore.Components;
using System.Drawing;

namespace Vivo_Task.RazorPages
{
    public partial class NavigateComponent
    {
        [Parameter] public string url { get; set; }
        protected override void OnAfterRender(bool firstRender)
        {
            if (firstRender)
            {
                NavigationManager.NavigateTo(url,true);
            }
            base.OnAfterRender(firstRender);
        }
    }
}